name: setup-renpy
description: Set up GitHub Actions workflow with Ren'Py SDK
author: remarkablemark
inputs:
  cli-version:
    description: CLI version
    required: false
    default: 8.2.1
  cli-name:
    description: CLI name
    required: false
    default: renpy
  rapt:
    description: Android Support (RAPT)
    required: false
    default: false
  renios:
    description: iOS Support (Renios)
    required: false
    default: false
  web:
    description: Web Platform Support (Renpyweb)
    required: false
    default: false
runs:
  using: node20
  main: dist/index.js
branding:
  icon: book-open
  color: yellow
