name: setup-renpy
description: Set up GitHub Actions workflow with Ren'Py CLI
author: remarkablemark
inputs:
  cli-name:
    description: CLI name
    required: false
    default: renpy-cli
  cli-version:
    description: CLI version
    required: false
    default: 8.5.1
  launcher-name:
    description: Launcher name
    required: false
    default: renpy-launcher
  rapt:
    description: Android Support (RAPT)
    required: false
    default: false
  renios:
    description: iOS Support (Renios)
    required: false
    default: false
  web:
    description: Web Platform Support (Renpyweb)
    required: false
    default: false
outputs:
  launcher:
    description: Ren'Py launcher path
runs:
  using: node24
  main: dist/index.js
branding:
  icon: book-open
  color: yellow
