name: build
on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: Lint codebase
        run: npm run lint

      - name: Check type
        run: npm run lint:tsc

      - name: Run tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run action
        uses: ./

      - name: Build artifact
        run: npm run build

      - name: Git commit and push
        if: github.actor == 'dependabot[bot]'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'feat: update build artifacts'

      - name: Check Git working tree
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Detected uncommitted changes. See status below:'
            git diff
            exit 1
          fi

  # action should work on a clean machine without building
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [7.7.1, 8.2.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run action
        uses: ./
        id: renpy
        with:
          cli-version: ${{ matrix.version }}
          rapt: true
          renios: true
          web: true

      - name: Locate binaries
        run: |
          command -v renpy-cli
          command -v renpy-launcher

      - name: Show launcher
        if: matrix.os != 'windows-latest'
        run: |
          ls $(command -v renpy-launcher)
          cat $(command -v renpy-launcher)

      - name: Check version
        if: matrix.os != 'windows-latest'
        run: |
          renpy-cli --version &> RENPY_VERSION
          if [[ $(cat RENPY_VERSION) != *'${{ matrix.version }}'* ]]; then
            echo 'Version does not match. See version below:'
            renpy-cli --version
            exit 1
          fi

      - name: Show help
        run: renpy-cli --help

      - name: Set projects directory
        if: matrix.os != 'windows-latest'
        run: renpy-launcher set_projects_directory ..

      - name: Set project
        run: renpy-cli ${{ steps.renpy.outputs.launcher }} set_project .

      - name: Check web support
        run: ls ${{ steps.renpy.outputs.launcher}}/../web/index.html

      - name: Build web
        if: matrix.os != 'windows-latest'
        run: |
          renpy-launcher web_build ${{ steps.renpy.outputs.launcher }}/../the_question --destination dist
          ls dist dist.zip
